openapi: 3.0.0
info:
  version: 1.0.0
  title: Swagger Fishstore
  license:
    name: MIT
servers:
  - url: http://localhost:8080/v1
paths:
  /fishs:
    get:
      summary: List fishs
      operationId: listFishs
      tags:
        - fishs
      parameters:
        - name: fishName
          in: query
          description: Restrict fish detail by name
          required: false
          schema:
            type: string
      responses:
        200:
          description: List of fishs
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Fishs"
    post:
      summary: Create a Fish
      operationId: createFish
      tags:
        - fishs
      parameters:
        - name: name
          in: query
          description: Restrict fish detail by name
          required: false
          schema:
            type: string
      responses:
        201:
          description: Null response
    put:
      summary: Modify a fish
      operationId: modifyFish
      tags:
        - fishs
      parameters:
        - name: id
          in: query
          description: Id of the fish to be modified
          required: true
          schema:
            type: integer
            format: int32
        - name: name
          in: query
          description: new name of the fish
          required: true
          schema:
            type: string
      responses:
        200:
          description: empty result

    delete:
      summary: Delete Fishs
      operationId: deleteFishs
      tags:
        - fishs
      parameters:
        - name: fishName
          in: query
          description: Name of the fish which be deleted
          required: false
          schema:
            type: string
      responses:
        200:
          description: Empty result
components:
  schemas:
    Fish:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Fishs:
      type: array
      items:
        $ref: "#/components/schemas/Fish"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
