
INSERT INTO fish (NAME) VALUES ('Discus');
INSERT INTO fish (NAME) VALUES ('Scalaire');
INSERT INTO fish (NAME) VALUES ('Pelmato');
INSERT INTO fish (NAME) VALUES ('Neolamprologus');
INSERT INTO fish (NAME) VALUES ('Brème commune');
INSERT INTO fish (NAME) VALUES ('Spirlin');
INSERT INTO fish (NAME) VALUES ('Barbus raye');
INSERT INTO fish (NAME) VALUES ('Suceur de pierres');
INSERT INTO fish (NAME) VALUES ('carpe Koi');
INSERT INTO fish (NAME) VALUES ('Neon bleu');
INSERT INTO fish (NAME) VALUES ('Cardinalis');
INSERT INTO fish (NAME) VALUES ('Tetra argente');
INSERT INTO fish (NAME) VALUES ('Nez rouge');
INSERT INTO fish (NAME) VALUES ('Tetra joyau');
INSERT INTO fish (NAME) VALUES ('Fantome rouge');
INSERT INTO fish (NAME) VALUES ('Le demoiselle noire');
INSERT INTO fish (NAME) VALUES ('Poisson clown');
INSERT INTO fish (NAME) VALUES ('Sergent major');
INSERT INTO fish (NAME) VALUES ('Demoiselle bicolore');
INSERT INTO fish (NAME) VALUES ('Requin marteau');
